apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: taskmanager
images:
  - name: taskmanager-backend
    newName: ghcr.io/your-user/taskmanager-backend
    newTag: latest
  - name: taskmanager-frontend
    newName: ghcr.io/your-user/taskmanager-frontend
    newTag: latest
