apiVersion: v1
kind: ConfigMap
metadata:
  name: taskmanager-config
  namespace: taskmanager
data:
  FLASK_ENV: production
  MONGO_DB_NAME: taskmanager
  MONGO_TIMEOUT_MS: "3000"
  CORS_ORIGINS: http://tasks.127.0.0.1.nip.io:8081
  BACKEND_HOST: backend
  BACKEND_PORT: "5001"
  DNS_RESOLVER: kube-dns.kube-system.svc.cluster.local
